### ISSUE TITLE
F407ZG vs F407VE config

### ISSUE THREAD

**Issue by jcw** [mcauser/BLACK_F407ZG#10]
The configuration of this board is somewhat inconsistent when compared to the BLACK_F407VE:

```
$ ls -l MicroPython-BLACK_F407*
-rw-r--r--  1 jcw  staff  449805 Jun  8 12:41 MicroPython-BLACK_F407VE.dfu
-rw-r--r--  1 jcw  staff  341621 Jun  8 12:41 MicroPython-BLACK_F407ZG.dfu
```

The large difference in size appears to be due to the VE having ethernet & networking enabled.
Might it be an idea to also enable it on this board, given that is has more pins and memory?

**Comment by mcauser** [comment]
Hey, I hadn't finished rolling out Ethernet to the ZE and ZG boards as I hadn't finished testing.
Damien suggested I merge the three BLACK_F407XX boards, so I was going to do it then.

The VE is on a 2.0 PCB and the ZE+ZG is on a 3.0 labelled PCB. There's a few differences in pins. The RMII pins are in the schematics pdf in /docs. Pretty straight forward to add to the Zx board defs. Just need to get some testing happening.

**Comment by jcw** [comment]
As in my other note: will be a while, but having Ethernet in the mix would be nice, even if it needs external h/w.
