### ISSUE TITLE
Something happened

### ISSUE THREAD

**Issue by K2AAE** [mcauser/BLACK_F407ZG#4]
The F407ZE and F407VE builds worked and are now loaded with MicroPython, the F407ZG Link output:

LINK build-BLACK_F407ZG/firmware.elf
arm-none-eabi-ld: warning: cannot find entry symbol _start; defaulting to 0000000000008000
   text    data     bss     dec     hex filename
      0       0       0       0       0 build-BLACK_F407ZG/firmware.elf
Create build-BLACK_F407ZG/firmware.dfu
GEN build-BLACK_F407ZG/firmware.hex

The firmware.dfu is 309 bytes
The firmware.hex is 34 bytes

**Comment by SpotlightKid** [comment]
Hmm, I don't really understand what you want to communicate with this issue?

**Comment by njustcjj** [comment]
Hi, K2AAE!
I also run into this problem.  And I compile another file as F407ZE (from mcauser's github, https://github.com/mcauser/BLACK_F407ZE) to compile F407ZG. It works!
The F407ZE and F407ZG have the same schematics. That's the point!
Wish you can fix the problem!

**Comment by SpotlightKid** [comment]
Fixed via #2.
