### ISSUE TITLE
Some errors.

### ISSUE THREAD

**Issue by RESBI** [mcauser/BLACK_F407ZG#5]
While I'm at this command: make BOARD=BLACK_F407ZG
Sth's going wrong:
resbi@XXXXXX:/XXXXXXX/micropython/ports/stm32$ make BOARD=BLACK_F407ZG
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
stm32lib submodule not found, fetching it now...
(cd ../.. && git submodule update --init lib/stm32lib)
Submodule 'lib/stm32lib' (https://github.com/micropython/stm32lib) registered for path 'lib/stm32lib'
Cloning into 'lib/stm32lib'...
^[
remote: Counting objects: 2138, done.
remote: Total 2138 (delta 0), reused 0 (delta 0), pack-reused 2138
Receiving objects: 100% (2138/2138), 8.00 MiB | 986.00 KiB/s, done.
Resolving deltas: 100% (1676/1676), done.
Checking connectivity... done.
Submodule path 'lib/stm32lib': checked out '1fe30d1446f2eba3730dc4b05e9ac0cf03bcf9bf'
mkdir -p build-BLACK_F407ZG/genhdr
GEN build-BLACK_F407ZG/genhdr/pins.h
GEN stmconst build-BLACK_F407ZG/modstm_qstr.h
make: *** No rule to make target 'lib/lwip/src/core/def.c', needed by 'build-BLACK_F407ZG/genhdr/qstr.i.last'.  Stop.

**Comment by SpotlightKid** [comment]
I can't reproduce this. Did you try to do a `make BOARD=BLACK_F407ZG clean` and try again?

**Comment by RESBI** [comment]
Yes I did..
But It still dosn't work:

resbi@XXXXXX:/XXXXXXX/micropython/ports/stm32$ make BOARD=BLACK_F407ZG clean
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
rm -rf build-BLACK_F407ZG
resbi@XXXXXX:/XXXXXXX/micropython/ports/stm32$ make BOARD=BLACK_F407ZG
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
mkdir -p build-BLACK_F407ZG/genhdr
GEN build-BLACK_F407ZG/genhdr/pins.h
GEN stmconst build-BLACK_F407ZG/modstm_qstr.h
make: *** No rule to make target 'lib/lwip/src/core/def.c', needed by 'build-BLACK_F407ZG/genhdr/qstr.i.last'.  Stop.

**Comment by SpotlightKid** [comment]
Did you compile `mpy-cross` from the root directory of the micropython repository with `make -C mpy-cross`?

Here's the exact sequence of commands to compile the firnware. Run them in a directory that doesn't contain a checkout of the micropython repo yet:

```
git clone https://github.com/micropython/micropython.git
cd micropython
git submodule update --init
pushd ports/stm32/boards
git clone https://github.com/SpotlightKid/BLACK_F407ZG.git
popd
make -C mpy-cross
pushd ports/stm32
make BOARD=BLACK_F407ZG clean
make BOARD=BLACK_F407ZG
```

**Comment by RESBI** [comment]
Thank you!
It works!

**Comment by briceparent** [comment]
For the record, to make it work on my Ubuntu 17.10, I had to launch the following 2 commands:
- before `make BOARD=BLACK_F407ZG`:
`sudo apt-get install gcc-arm-none-eabi`
- and before `make BOARD=BLACK_F407ZG deploy`:
`sudo pip install pyusb`
With that, it worked like a charm!
Thanks
