### ISSUE TITLE
external SRAM

### ISSUE THREAD

**Issue by jcw** [mcauser/BLACK_F407ZG#9]
Hello - this build works out of the box, including the on-board 2MB SPI flash. Thanks for sharing.

Have you tried the external SRAM? I've soldered a chip on there, and I vaguely remember seeing other µPy builds with S(D)RAM F(S)MC settings in their `mpconfigboard.h`, but it looks like this build hasn't gone there yet. Is there something I can do to try and help get external RAM going?

PS. This is static ram (F407 does not support SDRAM), maybe there's a difference. FWIW, the boards with SDRAM definitions are STM32F429DISC, STM32F769DISC, and STM32F7DISC).

**Comment by mcauser** [comment]
Hi @jcw Sorry I missed this issue. I purchased a `IS62WV51216BLL-55tli` for mine, as per the board docs. Haven't got around to experimenting with it yet. (I accidentally broke the first one with my dodgy old soldering iron)

The `DISC` board defs look like a good starting point. I listed the pins in the readme which I lifted from the board docs.

The W25Q16 SPI flash's WP and HOLD are connected to 3V3, so you can't use it in quad mode, just regular SPI mode.

**Comment by jcw** [comment]
Thx for the update - It'll be a while before I can go into this, but yeah - it's in a box, waiting for better times.
